### ISSUE TITLE
Archived samples not being removed from plates.

### ISSUE THREAD

**Issue by jovinden** [EPPIcenter/sampleDB-rpackage#12]
I want to archive sample 8045359599 because the tube is empty (dont want to delete so i can still access sample info retroactively). I threw away the physical tube, though sampledb still says it is on SeroX Plate 18. I want to delete SeroX Plate 18 so that I can upload new samples onto it. After I tried the archive finction I got the message "Deleted 0 Successfully" but the sample still shows up as on Plate 18. 

<img width="1436" alt="image" src="https://user-images.githubusercontent.com/61671020/174916618-0dfdcaea-c48f-4296-b080-8ab1651652d9.png">

**Comment by palmbri** [comment]
merged with fix#25
