### ISSUE TITLE
Cannot Delete Container (SeroX Plate 18)

### ISSUE THREAD

**Issue by jovinden** [EPPIcenter/sampleDB-rpackage#20]
I need to delete SeroX Plate 18, which is empty, so that i can upload new samples onto it. When I try to, I get disconnected from the server and SeroX Plate 18 is not deleted when I reload. 

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/61671020/176289243-dd119bc2-dc03-4af2-b22d-62c2bf06b0c2.png">

**Comment by palmbri** [comment]
Fix could be:
1. Change unique plate_name attribute in deleted_plate_matrix to instead by id (or have no constraint)
2. Check deleted plate names when uploading to check if a plate name is okay to use

**Comment by palmbri** [comment]
Consider wrapping sqlite statements in transactions - esp. deletions

**Comment by palmbri** [comment]
transactions are no longer
