### ISSUE TITLE
Plates incompletely uploaded 

### ISSUE THREAD

**Issue by jovinden** [EPPIcenter/sampleDB-rpackage#22]
I uploaded new samples onto SeroX Plate 16, 17, and 15 (the csv is labeled 18 but because of bug #20 i planned to upload them as if they were on SeroX Plate 15 and then move them to SeroX Plate 18). 

All the samples uploaded correctly except 4064914525, 4064914416, 8045359004 on SeroX Plate 16 and 4064914655 on SeroX Plate 17 (Micronics Barcodes). I noticed this when i tried to move the samples around, and got the error codes that these barcodes didn't exist. See screeenshot. There was no error messaging upon upload. 
<img width="1431" alt="image" src="https://user-images.githubusercontent.com/61671020/176326130-992f9f7d-68f8-4b80-98c2-6c8dadfcda1d.png">

Looking at SeroX Plate 16 first (serox16.csv): the three that were not uploaded had StudyCode=NA, which is my bad. So Bug#1: when there is an error that prevents one or more of the samples from being uploaded, the uploader should be notified and the upload should be canceled. If they can't all be uploaded, the version of the plate that is uploaded will be inaccurate. 

Now looking at SeroX Plate 17 (serox17.csv): the one that was not uploaded has nothing wrong. The only thing I can think of is that sampledb is having an issue with CollectionDate=NA. But when the sample is from a study that is not longitudinal (like MNP, where this sample is from), it should not require a date. So Bug#2 - fix the date requirement (if that is truly what is causing the issue), or else figure out what else is going wrong. 

I'm going to delete all the samples that i just uploaded (and their containers if possible) so that I can reupload correctly once we figure out the bug. Nothing was wrong with serox18 that i know of but just including it bc it was uploaded at the same time. 

[serox18.csv](https://github.com/EPPIcenter/sampleDB-rpackage/files/9006252/serox18.csv)
[serox17.csv](https://github.com/EPPIcenter/sampleDB-rpackage/files/9006253/serox17.csv)
[serox16.csv](https://github.com/EPPIcenter/sampleDB-rpackage/files/9006254/serox16.csv)

<img width="943" alt="image" src="https://user-images.githubusercontent.com/61671020/176326100-8ee8375b-126d-4ed0-8919-c109542c9e7a.png">

**Comment by palmbri** [comment]
For serox17.csv, it is the date 

![FormatMicronixLogisticalData](https://user-images.githubusercontent.com/103962129/176335774-e8af9acc-282d-4d7a-9c4d-57644417403e.png)

**Comment by palmbri** [comment]
database transactions will help here
