### ISSUE TITLE
Delete multiple samples at once 

### ISSUE THREAD

**Issue by jovinden** [EPPIcenter/sampleDB-rpackage#23]
Because of issue #22, I want to delete all the samples from SeroX Plate 16 and 17. Under "Delete & Archive Samples", I uploaded this deletesamples.csv. 
[deletesamples.csv](https://github.com/EPPIcenter/sampleDB-rpackage/files/9006340/deletesamples.csv)
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/61671020/176327868-ba6c1591-c423-4e46-99e9-54613eea34e7.png">

It pulls up all the samples from the csv on the right.  But when I click delete, it asks if I want to delete the following samples, and shows that none have been selected to delete. 

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/61671020/176327937-291109a6-a707-40d8-bb2d-d7b4cb46b56c.png">

Am I supposed to delete them all individually or is there already a way to delete them all at once that I am not seeing? If not, it would be helpful if there was a way to do this.

**Comment by palmbri** [comment]
cascade delete specimen on delete barcode + ask user if study subject should also be deleted

**Comment by palmbri** [comment]
merged with fix #25
