### ISSUE TITLE
How to handle samples that are empty, bad, or incorrect. AKA pathways for samples that do not physically exist. 

### ISSUE THREAD

**Issue by jovinden** [EPPIcenter/sampleDB-rpackage#25]
We need to have a system of dealing with samples that we are no longer using or are uploaded with incorrect information. This is gonna be a long wordy thing so buckle up. 

As I see it, once a sample has been uploaded to sampledb there are 4 states it can be in:

1. In use. (Default). The sample must have a location on a plate. 

2. Empty. (Depleted/Exhausted/Used Up). The physical sample tube has been thrown away because there is no sample left. In sampledb, it no longer needs to have a location on a plate. But sampledb needs to keep the MicronixBarcode, Participant, Date, StudyCode, SpecimenType so that we can retrospectively link the MicronixBarcode to the sample metadata. The user should be able to see that it is empty/depleted/whatever term we want to use so that it is clear that it cannot be used again in the future.

3.  Bad. The physical sample tube has been thrown away because there is something wrong with the sample. For example, bacterial growth, left at room temp, etc. As with an empty sample, sampledb no longer needs to have a location but does need to keep MicronixBarcode, Participant, Date, StudyCode, SpecimenType so that we can retrospectively link the MicronixBarcode to the sample metadata. The user should be able to see that it is "bad " or whatever term we want to use. 
It would be great to also include a brief description of why it was marked bad. Maybe the sample was working until Feb 22 2022 when it became contaminated. And looking back, I have data from this bad sample from before Feb 22 2022 that is still useable.
 
4. Incorrect. The file used to upload the sample had incorrect information. The user needs to be able to delete the sample from the database (ideally they would be able to delete several at once per issue #23 ) so that sampledb does not contain inaccuracies.

Currently, sampledb doesn't have all of these functionalities. I can delete samples (one at a time) (which was fixed in issue #15 ). There is a column in the Search view for "Exhausted" but I don't know how to edit the value. There is an archive feature but I'm not sure what it does or if it works - I think I archived something once but I have no idea how to view archived samples or whether they show up in the Search and how they are marked. I'm not on the VPN rn but I can attach screenshots of what exists now tomorrow.

Rough vision of how we could include the data:
<img width="1041" alt="image" src="https://user-images.githubusercontent.com/61671020/176570954-b6d49ccc-e0b5-432a-9984-b17cd8c10403.png">

**Comment by jovinden** [comment]
Thinking out loud: 

Column for NoLocation and NoLocationComment. 
Values of NoLocation must be %in% c(FALSE, Exhausted, Lost, Other).
If NoLocation==Other, NoLocationComment cannot = NA. Must contain some description entered by user.

**Comment by palmbri** [comment]
Use in app option. if that get's messy (UI component), use the file option.

**Comment by palmbri** [comment]
Archive workflows:

1) UPLOAD samples
	a) existing platename, all archived samples -> upload success
  		i) FAIL though if barcodes are not unique
  	b) existing platename, 1 or more active samples -> fore each, check well position with upload
  	c) no existing platename -> upload success

2) MOVE samples
	a) destination has all archived samples -> move success
	b) destination has one or more active samples -> for each, check well position with move
