### ISSUE TITLE
bug during large sample move: Unique constraint failed 

### ISSUE THREAD

**Issue by jovinden** [EPPIcenter/sampleDB-rpackage#38]
Attemping a move with the following files (Tracxer with suffix): 
[New folder.zip](https://github.com/EPPIcenter/sampleDB-rpackage/files/9107271/New.folder.zip)

![67945251456__472333A2-3F75-43F3-9F30-CCADE191AF1F](https://user-images.githubusercontent.com/61671020/178868955-cfa9e53a-5001-4647-a926-7ba5fa402ef0.jpeg)

SeroX Plate 8 Well D06 is causing issues

**Comment by palmbri** [comment]
merged with fix #25
