### ISSUE TITLE
Portability Issues

### ISSUE THREAD

**Issue by m-murphy** [EPPIcenter/sampleDB-rpackage#4]
Several things should be changed to make sampledb a more portable application. Currently the app assumes a linux style system, I think unnecessarily. To resolve, we should do the following

- [x] Place database in a location that is specific for the operating system (there are standard paths that are generally used)
- [x] remove usage of sudo for installation if possible, should not be necessary and only creates permissions issues
- [x] remove sqldiff as an external dependency. Checking for backup similarity can/should be done on a file identity basis (i.e. hash the file)
- [x] rework the backup mechanism -- questionable if this should be under the purview of sampledb or should be through some other process that is specific for the platform

**Comment by palmbri** [comment]
Reopening because work still needs to be tested on windows
