### ISSUE TITLE
Inactivated samples causing issues with sample move (I think)

### ISSUE THREAD

**Issue by jovinden** [EPPIcenter/sampleDB-rpackage#70]
Greetings. 

Attempted a sample move today with the following files: 
[move files other than SeroX Plate 19.zip](https://github.com/EPPIcenter/sampleDB-rpackage/files/9163354/move.files.other.than.SeroX.Plate.19.zip)
and 
[SeroX Plate 19_20220721_155923_withinactivatedbarcodes.csv](https://github.com/EPPIcenter/sampleDB-rpackage/files/9163355/SeroX.Plate.19_20220721_155923_withinactivatedbarcodes.csv)
which contains 2 samples that are inactivated. They are just empty tubes chillin on the plate because previously there wasn't a way to mark them as inactivated. When I hit move, I got this error: 
![image (14)](https://user-images.githubusercontent.com/61671020/180331240-4a4f2b93-728f-4698-88f6-7b1a95f424bd.png)

So then I was like oh, Brian inactivated those samples for me. I can remove them from the plate. So retried the upload with the following version of SeroX Plate 19: 
[SeroX Plate 19_20220721_155923.csv](https://github.com/EPPIcenter/sampleDB-rpackage/files/9163363/SeroX.Plate.19_20220721_155923.csv)

and I got the following error: 
![image (15)](https://user-images.githubusercontent.com/61671020/180331384-d20eba33-ba7e-4477-8c53-c241037541ca.png)

Because it doesn't give me a location for the orphaned samples, I think the missing inactivated samples are somehow being counted as orphaned? If thats not the case and there is another orphaned samples on the loose let me know so I can try to track it down.

**Comment by jovinden** [comment]
Or wait!! Maybe I still need to redo the big move before i do this move. Will try that and see. 

Ok when I tried to do the big move with all 32 files, it told me that SeroX plate 2 has inactivated samples. I dont know which sample on there has been inactivated -- could you tell me so I can get rid of it/make sure it was supposed to be inactivated? 
[New folder (1).zip](https://github.com/EPPIcenter/sampleDB-rpackage/files/9163405/New.folder.1.zip)
d

**Comment by palmbri** [comment]
![Screenshot from 2022-07-21 17-06-56](https://user-images.githubusercontent.com/103962129/180334984-f51b7ce3-706b-47aa-803c-0f4f40bc71ca.png)
